package constants



const POS_PURCHASE_JSON string=`{
    "ID": 1,
    "CreatedAt": "0001-01-01T00:00:00Z",
    "UpdatedAt": "0001-01-01T00:00:00Z",
    "DeletedAt": null,
    "Name": "",
    "Type": "",
    "Stage": "",
    "Maker": "",
    "Checker": "",
    "Approver": "",
    "Description": "POS Purchase Description here",
    "Status": "",
    "WorkflowLevels": 0,
    "DeletedOn": "0001-01-01T00:00:00Z",
    "AuditedOn": "0001-01-01T00:00:00Z",
    "SyncToken": 0,
    "Qrcode": null,
    "Barcode": null,
    "Attachment": null,
    "Version": 0,
    "Enabled": 0,
    "Locale": "",
    "TransactionType": "",
    "PosMemberID": 0,
    "PosDependantID": 0,
    "Amount": 5000,
    "User": "POSUser",
    "OrderNumber": "",
    "CustomerNumber": "A0118",
    "CustomerName": "Rolf Asbjornsen",
    "PosTransactionLogID": 0,
    "PosTransactionEodID": 0,
    "PurchaseItemList": [
        {
            "ID": 1,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "Name": "",
            "Type": "",
            "Stage": "",
            "Maker": "",
            "Checker": "",
            "Approver": "",
            "Description": "Purchase Item DESCRIPTION 1",
            "Status": "",
            "WorkflowLevels": 0,
            "DeletedOn": "0001-01-01T00:00:00Z",
            "AuditedOn": "0001-01-01T00:00:00Z",
            "SyncToken": 0,
            "Qrcode": null,
            "Barcode": null,
            "Attachment": null,
            "Version": 0,
            "Enabled": 0,
            "Locale": "en",
            "TransactionType": "",
            "ItemCode": "",
            "UnitCost": 300,
            "DiscountPercentage": 0,
            "Quantity": 3,
            "Location": "BAR",
            "LocationCode": "BAR",
            "UnitPrice": 500,
            "PosPurchaseID": 1,
            "PosTransactionLogID": 0,
            "AccountSet": "40002",
            "PriceList": "STD",
            "Category": "",
            "ExpDate": "",
            "LineType": 0,
            "StockItem": 0,
            "LineNumber": 0,
            "GLAccount": "",
            "GLNONSTKCR": "",
            "RequestDate": "",
            "TaxRate": 18
        },
        {
            "ID": 2,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "Name": "",
            "Type": "",
            "Stage": "",
            "Maker": "",
            "Checker": "",
            "Approver": "",
            "Description": "Purchase Item DESCRIPTION 2",
            "Status": "",
            "WorkflowLevels": 0,
            "DeletedOn": "0001-01-01T00:00:00Z",
            "AuditedOn": "0001-01-01T00:00:00Z",
            "SyncToken": 0,
            "Qrcode": null,
            "Barcode": null,
            "Attachment": null,
            "Version": 0,
            "Enabled": 0,
            "Locale": "",
            "TransactionType": "",
            "ItemCode": "",
            "UnitCost": 600,
            "DiscountPercentage": 0,
            "Quantity": 2,
            "Location": "BAR",
            "LocationCode": "BAR",
            "UnitPrice": 1000,
            "PosPurchaseID": 1,
            "PosTransactionLogID": 0,
            "AccountSet": "40002",
            "PriceList": "STD",
            "Category": "",
            "ExpDate": "",
            "LineType": 0,
            "StockItem": 0,
            "LineNumber": 0,
            "GLAccount": "",
            "GLNONSTKCR": "",
            "RequestDate": "",
            "TaxRate": 18
        },
        {
            "ID": 3,
            "CreatedAt": "0001-01-01T00:00:00Z",
            "UpdatedAt": "0001-01-01T00:00:00Z",
            "DeletedAt": null,
            "Name": "",
            "Type": "",
            "Stage": "",
            "Maker": "",
            "Checker": "",
            "Approver": "",
            "Description": "Purchase Item DESCRIPTION 3",
            "Status": "",
            "WorkflowLevels": 0,
            "DeletedOn": "0001-01-01T00:00:00Z",
            "AuditedOn": "0001-01-01T00:00:00Z",
            "SyncToken": 0,
            "Qrcode": null,
            "Barcode": null,
            "Attachment": null,
            "Version": 0,
            "Enabled": 0,
            "Locale": "",
            "TransactionType": "",
            "ItemCode": "",
            "UnitCost": 1000,
            "DiscountPercentage": 0,
            "Quantity": 1,
            "Location": "BAR",
            "LocationCode": "BAR",
            "UnitPrice": 1500,
            "PosPurchaseID": 1,
            "PosTransactionLogID": 0,
            "AccountSet": "40002",
            "PriceList": "STD",
            "Category": "",
            "ExpDate": "",
            "LineType": 0,
            "StockItem": 0,
            "LineNumber": 0,
            "GLAccount": "",
            "GLNONSTKCR": "",
            "RequestDate": "",
            "TaxRate": 18
        }
    ]
}`